version: '3'

services:
  web:
    build:
      context: ./findmypart
      dockerfile: Dockerfile
    command: gunicorn findmypart.wsgi:application --bind 0.0.0.0:8000 --workers=4 --threads=4 --worker-class=gthread
    volumes:
      - ./findmypart:/code/findmypart
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

  api:
    build:
      context: ./findmypart_api
      dockerfile: Dockerfile
    command: uvicorn main:app --host=0.0.0.0 --port=8000 --workers=2 --proxy-headers
    ports:
      - "8080:8000"
    volumes:
      - ./findmypart_api:/code/findmypart_api
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
      - api
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data: