# Generated by Django 3.2.25 on 2024-07-13 18:13

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('partfinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Название'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['name'], name='partfinder__name_5fe491_idx'),
        ),
        migrations.AddIndex(
            model_name='model',
            index=models.Index(fields=['name'], name='partfinder__name_fb2d82_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(django.db.models.expressions.F('json_data__is_new_part'), name='json_data__is_new_part_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['name'], name='partfinder__name_b3ed23_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['mark_id', 'model_id'], name='partfinder__mark_id_12bd6a_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['mark_id'], name='partfinder__mark_id_e740d6_idx'),
        ),
    ]
